### PR TITLE
mainly left to right and right to left combining

### PR DESCRIPTION
**Pull request by nathanielstenzel**
Reduce the left to right and the right to left code into one section.
Make sure that the raster.width is really used as the raster.width. It was rastering for raster.width+1.

### CODE REVIEW

**Comment by ghost** [comment]
Okay so to avoid the 5 merges, i tried your branch directly:

My version - run over https://raw.githubusercontent.com/openhardwarecoza/LaserWeb/master/i/raster/calibration.jpg produces:

peter

Yours produce:

nathaniel

Note how the return row looks like a solid move all the way through?
I can also see in the numbers you are off on the return stroke by 1 pixel... It doesnt line up vertically

I suggest you:
1.  kill your repo
2.  Install from my repo and get it running first. Play with it for a while.  
3.  Observe the two calibration and test files under https://raw.githubusercontent.com/openhardwarecoza/LaserWeb/master/i/raster/  as its working now
4.  Look at number of gcode moves.  Optimise that (removing unnecessary G0s would be the win)

To elaborate on a "want"

Right now it does:

ariel1

But we want it to do:

zigzag

When i did get it to do the zig zag above though, my code couldnt do the calibartion.jpg successfully anymore:

What is suppose to look like:
calibr

Came out like:
paper js

So need to find a compromise where calibration.jpg comes out like now (all lined up, not missing any color shade, not loosing the 1px border) but where the random portrait comes out with less G0 moves

**Comment by ghost** [comment]
PS: Developer console in Chrome will spit out some stats to help with guaging optimisation: The optimised by number of lines = the skip++ in each round where it counts instead of writes)

stats

**Comment by nathanielstenzel** [comment]
While working on bucket_mill, I eventually found that it is bad to only consider less gcode moves. You may be missing important moves if you do. I thought I was making things better when reducing my gcode moves, but I was making them worse. I just wanted to put that out there.

**Comment by ghost** [comment]
Agreed,. already encountered that - see how i screwed up calibration.jpg runs when I got the lady to be like i wanted - case 1 = with a border and case 2 without...   Less isnt more, but still, less is important. The bottleneck here is serial speed (; so less data is important.  Binary raster is the way to go but I am tired of waiting for next year, like Arthur Wolf says, better to have a crappy solution now, than nothing

**Comment by nathanielstenzel** [comment]
laserweb-x
That is yours. Mine does not look so good.
I am closing this pull request.

**Pull request closed without merging**
