### PR TITLE
added ubuntu installation instructions to readme

### PR DESCRIPTION
**Pull request by adeebshihadeh**
also cleaned up some formatting/markdown issues

### CODE REVIEW

**Comment by ghost** [comment]
Thanks!

**Comment by adeebshihadeh** [comment]
No problem. This is a way better solution that dealing with visicut :)

**Comment by ghost** [comment]
Afraid so.  it took me less to fork and work off off @andrewhodel incredibly smooth coded work and get a new product out, than it did to try and get the gcode driver in visicut just to talk to the board!

**Comment by cojarbi** [comment]
What are the requirements regarding OS type on the RPI. I unable to finish installing node.js. . Im running this on the same sd as octoprint

**Comment by ghost** [comment]
Try @Protoneer 's Pi Image or install script https://github.com/Protoneer/RPI-CNC-Config-Scripts/blob/master/scripts/wip-007-install-laserweb.sh

**Comment by cojarbi** [comment]
Did Protoneer and then installed Laserweb but it takes infinity to load.

**Pull request merged**
