### PR TITLE
Add .nvmrc file.

### PR DESCRIPTION
**Pull request by danawoodman**
If the users is using nvm, the .nvmrc file will automatically switch over to the proper version of node. If they do not have the proper version they can run `nvm install` and then `nvm use` to get the right version.

### CODE REVIEW

**Comment by andrewhodel** [comment]
Why use nvm at all?

**Comment by danawoodman** [comment]
@andrewhodel so that you can easily manage using different node versions in different projects easily. It automatically switches you to the proper node version when you `cd` into a directory. Also makes it easy to install the right version on demand by running `nvm install`: https://github.com/creationix/nvm

**Comment by andrewhodel** [comment]
Seems to be better to stabilize node, there's only so many structures you need in the core functionality and then it practically works for everything.

Then with npm you have modules, which you should still rewrite to understand in today's online world.

I'd be interested to hear of some new genuinely novel ideas, but it seems that just about everything is covered with node and npm.  Where have you run into trouble with needing multiple node versions?

**Comment by danawoodman** [comment]
Considering that this project requires installing a specific version of node, targeting that in an easy way using something like `nvm` improves the user experience.

I work on a wide variety of projects (as do most developers) that range from node `v0.10` to `v5.2`. Having the right version activated is important and a tool like `nvm` makes it easy to not have to remember to switch versions when you move to a particular project/codebase.

Besides, using `nvm` is optional and people without it see no change or effect.

Also, "stabilizing node" seems to be a bit out of the scope of this Pull Request.

**Comment by andrewhodel** [comment]
com.org.this.that.eventually.that.gets.old

I guess that's the reality of not starting from the basics on each project, team or no team.

**Comment by danawoodman** [comment]
I have no idea what you're saying.

**Comment by danawoodman** [comment]
If the maintainer wants this feature merged, then great. Otherwise, he can reject it. That's all I've got to say about the issue.

**Comment by ghost** [comment]
@danawoodman , I actually made @andrewhodel a maintainer as well in the beginning, because most of the node.js, socket.io, and serial handling code was written by @andrewhodel in his https://github.com/andrewhodel/reprapweb and https://github.com/andrewhodel/grblweb projects, and the Millcrum/dxf/svg-> Gcode comes from his https://github.com/andrewhodel/millcrum project too.  
(; So yeah , pretty key to my operation hehe

That said, Andrew hates Windows.  And windows hates SerialPort (well, not really but you get my drift), and users hate compiling so forcing a specific node.js version, allows me to use the precompiled native modules SerialPort needs, in order to work with windows.  

So we really only need to force windows users to a specific version. 

There's thus two reasons why I would prefer not to overcomplicate the install even more, by adding nvm:
1.  Its only one of the platforms where it's an issue, windows. 
2.  I want to move away from Nodejs+Serialport anyway (I am very open to alternatives. Andrew suggested the Chrome serial API - and we are anyway telling users to use chrome for the UI, so why not). Or option 2, integrate with existing serial port json server (but then we need to get the smoothie, marlin, lasaurgrbl buffers into it.  Or write our own little Golang serial port bridge so we can distribute it as precompiled ourselves...  Opening a new Issue for us to track this instead

**Comment by danawoodman** [comment]
I'm a little confused. The nvmrc file locks down to a particular node version which is what it sounds like you want? Or am I missing something?

**Pull request closed without merging**
