### PR TITLE
Added Docker build

### PR DESCRIPTION
**Pull request by jcoffland**
This is a nice quick way to test out or run LaserWeb in a clean environment with out building a full VM.

### CODE REVIEW

**Comment by ghost** [comment]
Thank you!

**Comment by ghost** [comment]
Can you please add instructions to the Wiki too

**Comment by jcoffland** [comment]
Sure, done.

**Comment by mmemetea** [comment]
I'm trying to run LaserWeb on a Mac through Docker. Everything looks fine except the serial port aren't apparently visible in the LaserWeb interface. Are some additional arguments required to be declared in the Docker command to make the serial port available? (http://stackoverflow.com/questions/24225647/docker-any-way-to-give-access-to-host-usb-or-serial-device)
I thought that something like
'docker run -p 8000:8000 --device=/dev/ttyUSB0 -d --name laserweb laserweb'
should help, but apparently it doesn't...
Any suggestion?

**Comment by ghost** [comment]
@jcoffland   ?   (:

**Comment by jcoffland** [comment]
I've also seen devices added to Docker instances like this:

```
docker run -p 8000:8000 --device=/dev/ttyUSB0:/dev/ttyUSB0 -d --name laserweb laserweb
```

You should make sure that the permissions are set correctly on `/dev/ttyUSB0`.  The permissions inside the Docker instance should not be an issue but in the host system they have to be right.  The link you provided above also says you might need to add `--privileged`.

**Comment by jcoffland** [comment]
Also you need to be sure that `/dev/ttyUSB0` is the correct name for your serial device.  I suggest testing it manually first with something like `minicom`.

**Comment by mmemetea** [comment]
You're right about the name of the serial interface, in my case it should be `/dev/tty.usbmodem1414` (verified by running Printer-Run fro example). However, typing the command `docker run -p 8000:8000 --device=/dev/tty.usbmodem1414:/dev/tty.usbmodem1414 -d --name laserweb laserweb` gives me back the following error:

> server
> error 500
> error gathering device information while adding custom device ''/dev/tty.usbmodem1414": lstat
> /dev/tty.usbmodem1414: no such file or directory''

Not sure what to do next...

**Comment by jcoffland** [comment]
This does not appear to be an issue with the Docker setup I created for LaserWeb.  Sorry I don't have the time to help you with this further.  You need to figure out your USB device issues first.

**Comment by mmemetea** [comment]
Yes, I think you're right. I'll find another way. Thank you anyhow...

**Comment by mmemetea** [comment]
Apparently the default settings for the VM that run under Docker hasn't the USB enabled. Need to fix that.

**Pull request merged**
